version: "3"
services:
  app:
    image: web-front
    build:
      context: .
      dockerfile: prod.Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/.next
    ports:
      - 3000:3000
    container_name: web-front-prod
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app